package bo.com.offercruz.entidades;
// Generated 13-oct-2014 18:48:07 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contenido generated by hbm2java
 */
public class Contenido  implements java.io.Serializable {


     private Integer id;
     private int tipoContenido;
     private String titulo;
     private String descripcion;
     private int estado;
     private Date fechaPublicacion;
     private Date fechaExpiracion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<Detallecontenido> detallecontenidos = new HashSet<Detallecontenido>(0);
     private Set<Imagencontenido> imagencontenidos = new HashSet<Imagencontenido>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Contenido() {
    }

	
    public Contenido(int tipoContenido, String titulo, String descripcion, int estado, Date fechaPublicacion, Date fechaExpiracion, Date fechaCreacion, Date fechaModificacion) {
        this.tipoContenido = tipoContenido;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.estado = estado;
        this.fechaPublicacion = fechaPublicacion;
        this.fechaExpiracion = fechaExpiracion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }
    public Contenido(int tipoContenido, String titulo, String descripcion, int estado, Date fechaPublicacion, Date fechaExpiracion, Date fechaCreacion, Date fechaModificacion, Set<Detallecontenido> detallecontenidos, Set<Imagencontenido> imagencontenidos, Set<Solicitud> solicituds) {
       this.tipoContenido = tipoContenido;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaPublicacion = fechaPublicacion;
       this.fechaExpiracion = fechaExpiracion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.detallecontenidos = detallecontenidos;
       this.imagencontenidos = imagencontenidos;
       this.solicituds = solicituds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTipoContenido() {
        return this.tipoContenido;
    }
    
    public void setTipoContenido(int tipoContenido) {
        this.tipoContenido = tipoContenido;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Detallecontenido> getDetallecontenidos() {
        return this.detallecontenidos;
    }
    
    public void setDetallecontenidos(Set<Detallecontenido> detallecontenidos) {
        this.detallecontenidos = detallecontenidos;
    }
    public Set<Imagencontenido> getImagencontenidos() {
        return this.imagencontenidos;
    }
    
    public void setImagencontenidos(Set<Imagencontenido> imagencontenidos) {
        this.imagencontenidos = imagencontenidos;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


