package bo.com.offercruz.entidades;
// Generated 13-oct-2014 18:48:07 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer id;
     private Imagen imagen;
     private Categoria categoria;
     private String descripcion;
     private String nombre;
     private int estado;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private int idEmpresa;
     private int tipoOferta;
     private Double precioUnitario;
     private Set<Detallesolicitud> detallesolicituds = new HashSet<Detallesolicitud>(0);
     private Set<Detallecontenido> detallecontenidos = new HashSet<Detallecontenido>(0);

    public Oferta() {
    }

	
    public Oferta(Imagen imagen, Categoria categoria, String descripcion, String nombre, int estado, Date fechaCreacion, Date fechaModificacion, int idEmpresa, int tipoOferta) {
        this.imagen = imagen;
        this.categoria = categoria;
        this.descripcion = descripcion;
        this.nombre = nombre;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.idEmpresa = idEmpresa;
        this.tipoOferta = tipoOferta;
    }
    public Oferta(Imagen imagen, Categoria categoria, String descripcion, String nombre, int estado, Date fechaCreacion, Date fechaModificacion, int idEmpresa, int tipoOferta, Double precioUnitario, Set<Detallesolicitud> detallesolicituds, Set<Detallecontenido> detallecontenidos) {
       this.imagen = imagen;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.idEmpresa = idEmpresa;
       this.tipoOferta = tipoOferta;
       this.precioUnitario = precioUnitario;
       this.detallesolicituds = detallesolicituds;
       this.detallecontenidos = detallecontenidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public int getTipoOferta() {
        return this.tipoOferta;
    }
    
    public void setTipoOferta(int tipoOferta) {
        this.tipoOferta = tipoOferta;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Set<Detallesolicitud> getDetallesolicituds() {
        return this.detallesolicituds;
    }
    
    public void setDetallesolicituds(Set<Detallesolicitud> detallesolicituds) {
        this.detallesolicituds = detallesolicituds;
    }
    public Set<Detallecontenido> getDetallecontenidos() {
        return this.detallecontenidos;
    }
    
    public void setDetallecontenidos(Set<Detallecontenido> detallecontenidos) {
        this.detallecontenidos = detallecontenidos;
    }




}


